version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: user1
    coins: ["10000token", "100000000stake" ]
  - name: user2
    coins: ["10000token", "100000000stake"]
  - name: cp1
    coins: ["10000token", "100000000stake"]
  - name: cp2
    coins: ["10000token", "100000000stake"]
  - name: ct1
    coins: ["10000token", "100000000stake"]
  - name: ct2
    coins: ["10000token", "100000000stake"]

validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
